name: Build C Program with MSVC

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Install MinGW 12.2.0
        uses: deevroman/setup-mingw@0.0.1

      - name: Compile C Program
        run: |
          gcc -o run-in-background.exe run-in-background.c

      - name: Save Result
        uses: actions/upload-artifact@v4.6.0
        with:
          name: program-x64
          path: run-in-background.exe
