name: Build C Program with MSVC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 'latest'

      - name: Compile C Program with cl.exe
        run: |
          cl /EHsc /Fe:your_program.exe your_program.c

      - name: Save Result
        uses: actions/upload-artifact@v4.6.0
        with:
          path: your_program.exe
